# Generated by Django 2.2.4 on 2022-10-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favbook', '0002_auto_20221004_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_PW',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='ahmad@hamdan.com', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
    ]
