# Generated by Django 2.2.4 on 2022-10-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favbook', '0003_auto_20221004_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='no description for this one', max_length=255),
        ),
    ]
